<?php
include_once 'classes/classLearner.php';
/**
 * Inherits from classLearner;<br>
 * CRUD access;<br>
 * Able to work on multiple records;<br>
 *
 * @author rory
 */
class classAdmin extends classLearner  {

	private $LearnerCreateDate;
	private $LearnerCreateUserId;
	private $LearnerModDate;
	private $LearnerModUserId;
	private $NewLearnerId;
	private $NewLearnerFormData;
	private $LearnerList;
	private $Message;

	public function __construct() {
		parent::__construct();
//		print_r($this->CourseList);
//		print_r($this->Company);
//		print_r($this->PrettyHeaderMap);

		/**
		 * 
		 *  TODO ===> Collect logged Admin User Id
		 */
		$this->Today = gmdate("Y-m-d H:i:s", strtotime(" + 2 hours"));
		$this->LearnerCreateUserId = 1;
		$this->LearnerModUserId    = 1;
		$this->LearnerCreateDate   = $this->Today;
		$this->LearnerModDate      = $this->Today;
		$this->buildLearnerList();
//		print_r($this->CourseList);
//		self::function();
	}

	public function getLearnerList() {
		/**
		 * Returns array of all learners
		 * @internal Return array of all learners generated by $this->buildLearnerList()
		 * @return array
		 */
//		$this->buildLearnerList();
		return $this->LearnerList;
	}
	
	public function addNewLearner($formData) {
//		echo "addNewLearner()<br>";
//		print_r($formData);
		$this->NewLearnerFormData = $formData;
		if (!$this->checkExists('User', $this->NewLearnerFormData['UserName'])) {
			$this->createNewLearner();
			$message = "<p>Successfully added new learner to the database.</p>";
		}
		else {
			$message = "<p class='btn-danger'>The Email Address / Username you have selected already exists in the database.</p>";
		}
		echo $message;
	}
	
	private function createNewLearner() {
		/* TODO =====> Check if FName & SName are already in use or not. Do we need to?
		 * ==========> If we don't do this, duplicate Learners could exist with different
		 * ==========> Usernames. 
		 * Do we care? Added ID Number - need unique identifier for CPD...
		 */
//		echo "createNewLearner()";
		$Fields    = '(';
		$Values    = 'VALUES (';
		$counter   = 0;
		$CompanyId = 'zzzz';
		$checkUnique = FALSE;
		foreach ($this->NewLearnerFormData as $FieldName => $FieldValue) {
			if (($FieldName != 'PHPSESSID') && ($FieldName != 'CourseId')) {
				if ($counter == 0) {
					$Fields .= "`$FieldName`";
					$Values .= "'$FieldValue'";
					$counter++;
				}
				else {
					$Fields .= ", `$FieldName`";
					$Values .= ", '$FieldValue'";
					$counter++;
				}
			}
		}
		$Fields .= ", `CreateUser`, `CreateDate`, `ModUser`, `ModDate`)";
		$Values .= ", " . $this->LearnerCreateUserId . ", '" . $this->LearnerCreateDate . "', " . $this->LearnerModUserId . ", '" . $this->LearnerModDate . "')";
		$SQL = "INSERT `Learner` $Fields $Values";
		$Message = $this->execSQL($SQL, 'I');
		$this->NewLearnerId = $this->LastInsertedId;
//		print_r($this->NewLearnerFormData);
		if ($Message) {
			$this->updateLearnerData($this->NewLearnerFormData['FName'], $this->NewLearnerId);
			$this->addLearnerCourse($this->NewLearnerId, $this->NewLearnerFormData['CourseId']);
		}
	}

	private function addLearnerCourse($LearnerId, $CourseId) {
		$SQL = "INSERT `LearnerCourse` (`LearnerId`, `CourseId`, `RegDate`) VALUES ($LearnerId, $CourseId, '$this->Today')";
		if (!$this->execSQL($SQL, 'I')) {
			$this->Message .= "<br>Course not added. Please add a course to the Learner's file.";
		}
	}
	
	protected function buildLearnerList() {
		$SQL = "SELECT l.`LearnerId` as 'Id', l.`SName`, l.`FName`, l.`UserName`, l.`Hash`, l.`Email`, l.`CompanyId`, c.`CompanyDesc`, l.`LastLogin` FROM `Learner` l JOIN `Company` c ON (l.`CompanyId` = c.`CompanyId`) ORDER BY l.`SName`, l.`FName`";
		$result = $this->query($SQL);
		while ($row = mysqli_fetch_assoc($result)) {
			$this->LearnerList[$row['Id']] = $row;
		}
	}
	
	protected function addNewCourse($Code, $Desc, $UserId) {
		
	}
}

?>
